name: Check Lua

on:
  push:
    branches:
      - main
    paths:
      - '**.lua'
      - '!spec/**'

  pull_request:
    branches:
      - main
    paths:
      - '**.lua'
      - '!spec/**'

  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Lua
        uses: leafo/gh-actions-lua@35bcb06abec04ec87df82e08caa84d545348536e # v10.0.0

      - name: Setup LuaRocks
        uses: hishamhm/gh-actions-luarocks@master

      - name: Run luacheck
        run: luarocks install luacheck && luacheck . --no-cache --formatter TAP --include-files "**/*.lua" --exclude-files spec .lua .luarocks
