name: Test Windows Check (temporary)

on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Setup Microsoft Visual C++ Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0

      - name: Setup Lua
        uses: hishamhm/gh-actions-lua@master
        with:
          luaVersion: 5.4
          buildCache: false

      - name: Setup LuaRocks
        uses: hishamhm/gh-actions-luarocks@master
        with:
          luarocksVersion: "3.11.0"

      - name: Build fenster
        run: luarocks make

      - name: Run a basic test
        run: lua -e "local fenster = require('fenster');print(fenster.time())"
